#pragma once
#include "Command.h"
#include "../../headers/commands/LoginCommand.h"
#include "../../headers/commands/RegisterCommand.h"
#include "../../headers/commands/LogoutCommand.h"
#include "../../headers/commands/CreateProjectCommand.h"
#include "../../headers/commands/AddUserToProjectCommand.h"
#include "../../headers/commands/AddStageCommand.h"
#include "../../headers/commands/StartStageCommand.h"
#include "../../headers/commands/FinishStageCommand.h"
#include "../../headers/commands/FinalizeProjectCommand.h"
#include "../../headers/commands/CreateTaskCommand.h"
#include "../../headers/commands/AssignTaskCommand.h"
#include "../../headers/commands/ChangeTaskStatusCommand.h"
#include "../../headers/commands/ChangeTaskPriorityCommand.h"
#include "../../headers/commands/GradeTaskCommand.h"
#include "../../headers/commands/AddCommentCommand.h"
#include "../../headers/commands/SaveCommand.h"
#include "../../headers/commands/LoadCommand.h"
#include "../../headers/commands/MoveTaskToStageCommand.h"
#include "../../headers/commands/ViewProfileCommand.h"
#include "../../headers/commands/ListProjectsCommand.h"
#include "../../headers/commands/ViewProjectCommand.h"
#include "../../headers/commands/ViewTaskCommand.h"
#include "../../headers/commands/MyTasksCommand.h"
#include "../../headers/commands/UpcomingTaskCommand.h"
#include "../../headers/commands/ListAllProjectsCommand.h"
#include "../../headers/commands/ListAllTasksCommand.h"
#include "../../headers/commands/StudentReportCommand.h"
#include "../../headers/commands/StageReportCommand.h"
#include "../../headers/commands/RemoveUserCommand.h"
#include "../../headers/commands/ListTasksCommand.h"
#include "../../headers/commands/ReviewTaskCommand.h"
#include "../../headers/commands/ApproveTaskCommand.h"
#include "../../headers/commands/HelpCommand.h"
#include "../../headers/commands/SearchTasksCommand.h"
#include "../../headers/commands/FilterTasksCommand.h"
#include "../../headers/commands/ViewHistoryCommand.h"
#include "../../headers/commands/AddTagCommand.h"

class CommandFactory {

public:

	static Command* generateCommand(std::string& cmdLine, std::vector<std::string>& tokens);
};